input.onButtonPressed(Button.A, function () {
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 40)
    basic.pause(2500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 45)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 45)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 40)
    basic.pause(2500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
})
input.onButtonPressed(Button.B, function () {
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 60)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 65)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 65)
    basic.pause(600)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 40)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
})
DFRobotMaqueenPlus.I2CInit()
